version: '3.8'

services:
  memcached:
    image: memcached:1.6.22
    container_name: memcached_cache
    ports:
      - "11211:11211"
    restart: always

  openresty:
    image: openresty/openresty:1.21.4.1-3-focal
    container_name: openresty_proxy
    ports:
      - "80:80"
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./openresty/lua:/usr/local/openresty/lua:ro
    links:
      - golang_service
      - memcached
    restart: always

  golang_service:
    build: ./golang_service
    container_name: golang_backend
    ports:
      - "8081:8081"
    restart: always